### ISSUE TITLE
Finding dSYM file on macOS can be very slow

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/moria#11]
I have to run `locate_debug_symbols` in a spin loop, because it takes quite a time for spotlight to index it. I have even got >60s several times.

**Comment by bjorn3** [comment]
https://github.com/bjorn3/pretty_backtrace/commit/5be873ac6542991368d77306a46c99921d112e16 worked around this by adding a fast path for the case of the current executable being at `target/<channel>/???` and the debuginfo being at `target/<channel>/{deps,examples}`. (Eg when using `cargo run`) It also adds a spin loop waiting for spotlight to find the debuginfo.

**Comment by luser** [comment]
[We've got code](https://github.com/gimli-rs/moria/blob/83e27832cd70f33ce835726d6b91f064ae0cb50f/src/lib.rs#L215-L228) to do simple path manipulation to support locating dSYM files on non-macOS systems, maybe we should try that first even on macOS, and only fall back to using Spotlight if that doesn't work?

**Comment by bjorn3** [comment]
> We've got code to do simple path manipulation to support locating dSYM files on non-macOS systems, maybe we should try that first even on macOS, and only fall back to using Spotlight if that doesn't work?

Done and I also extended it to work for cargo, which doesn't put the dSYM in the same dir as the executable.
