### ISSUE TITLE
Replace usage of CoreFoundation-sys with core-foundation

### ISSUE THREAD

**Issue by luser** [gimli-rs/moria#3]
I don't know why I used `CoreFoundation-sys` https://crates.io/crates/CoreFoundation-sys except that maybe it was the first thing I found? Servo has a `core-foundation` crate that wraps things in a slightly higher-level API which provides a `Drop` implementation and should make the existing code in `moria` much simpler: https://crates.io/crates/core-foundation .

**Comment by bjorn3** [comment]
This was done in 57b620c5563fa5f63f4a6807d61a5bf51508ebd7.

**Comment by luser** [comment]
So it was, thanks!
