### ISSUE TITLE
Bring this crate up to a releaseable state

### ISSUE THREAD

**Issue by luser** [gimli-rs/moria#4]
Here's a list I dropped in the initial PR:
- [ ]     Add some tests
- [ ]     Add crate-level docs
- [ ]     Flesh out the README
- [x]     Add a LICENSE file / choose a license (whatever gimli is using is fine)
- [x]     Add some CI
- [x]     Sort out fork of `object` crate

**Comment by tromey** [comment]
Cargo.toml references a (local?) branch of the object crate; this also should be fixed before release.

**Comment by luser** [comment]
> Cargo.toml references a (local?) branch of the object crate; this also should be fixed before release.

Oh, good call! There's [a PR open for those changes](https://github.com/gimli-rs/object/pull/39), and I see you've already commented there. :)

**Comment by dvc94ch** [comment]
Any progress on this? I'm really interested in using it.

**Comment by dvc94ch** [comment]
Done in #41
