### ISSUE TITLE
Support for PE -> PDB lookup

### ISSUE THREAD

**Issue by schultetwin1** [gimli-rs/moria#44]
I realize this crate is called "locate-dwarf" but I'd love to add support for finding a PDB based on a PE. Is that something you'd be open to?

**Comment by dvc94ch** [comment]
I guess that fits within the scope of this crate.

**Comment by luser** [comment]
The original intention was to have support for cross-platform debug info, but yeah, the current crate name is unfortunate in that respect. :)

**Comment by schultetwin1** [comment]
I created gimli-rs/object#298 in order to support this functionality. Once that PR is completed and makes it into the next release, the `object` crate will have the ability to read `pdb_info()` which we can use to get the path to the PDB.

**Comment by schultetwin1** [comment]
That PR was completed. Once `object` has a new release I'll do this work to add PDB searching. It should be pretty easy.
